version: '3.8'

services:
  php:
    build: .
    container_name: php_app
    ports:
      - "8090:80"
    #volumes:
      #- ./:/var/www/html
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: php_app_db
    environment:
      MYSQL_DATABASE: myapp
      MYSQL_USER: user
      MYSQL_PASSWORD: pass
      MYSQL_ROOT_PASSWORD: rootpass
    volumes:
      - db-data:/var/lib/mysql
      - ./table_structure.sql:/table_structure.sql
    ports:
      - "3306:3306"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_USER: user
      PMA_PASSWORD: pass
    ports:
      - "8081:80"
    depends_on:
      - db

volumes:
  db-data:
